blog/urls.py
from django.urls import path
from . import views

"""
the app_name variable allows us to organise URLs by application and use the
name when reffering to them.
"""
app_name = 'blog'

urlpatterns = [
    # post views
    # path('', views.post_list, name='post_list'),
    path(
        '',
        views.PostListView.as_view(),
        name='post_list'
    ),
    path(
        'tag/<slug:tag_slug>/',
        views.PostListView.as_view(),
        name='post_list_by_tag'
    ),
    path(
        '<int:year>/<int:month>/<int:day>/<slug:post>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        '<int:post_id>/comment/',
        views.post_comment,
        name='post_comment'
    ),

    path(
        'comment/<int:comment_id>/edit/',
        views.edit_comment,
        name='edit_comment'
    ),
    path(
        'comment/<int:comment_id>/delete/',
        views.delete_comment,
        name='delete_comment'
    ),
]

"""
Note: We use angle brackets to capture values from the URL. Any value specified
in the URL pattern as a <parameter> is captured as a string. You use path
converters such as <int:year>, to specifically match and return an integer.
E.g: <slug:post> would specifically match a slug.

Also note that if class based views are going to be used for post list then the
blog/list.html template needs to change as the generic view passes the page
number reuqested in a variable called page_obj. So line 22:
{% include "pagination.html" with page=posts %}  now becomes:
{% include "pagination.html" with page=page_obj %}
"""

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="{% static 'css/blog.css' %}" rel="stylesheet" />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <div class="wrapper">
        <div class="content">
            <h1>
                <a id="stupidJs" href="{% url 'blog:post_list' %}">The Inkwell Collective</a>
            </h1>
            {% block content %}
            {% endblock %}
        </div>
        <div class="sidebar">
            <div class="sidebarinner">
                <div class="auth-links">
                    {% if user.is_authenticated %}
                    <div class="auth-message">
                        <p>Welcome back, {{ user.username }}!</p>
                        <form id="logout-form" method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="nobutton">Logout</button>
                        </form>
                    </div>
                    {% else %}
                        <div>
                            <a class="nobutton" href="{% url 'login' %}">Login</a> | 
                            <a class="nobutton" href="{% url 'register' %}">Register</a>
                        </div>
                    {% endif %}
                </div>
                
                <h2>Most Commented Posts</h2>
                <div class="most-commented">
                    {% for post in most_commented_posts %}
                        <a href="{{ post.get_absolute_url }}" class="most-commented-link">
                            {{ post.title }}
                            <span class="comment-count">
                                <i class="fas fa-comment"></i> {{ post.comment_count }}
                            </span>
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>   
    </div>
    <script href="{% static 'js/script.js' %}" rel="javascript">
        const hoverEle = document.getElementById('stupidJs');

        function addHoverStyle() {
            hoverEle.style.backroundColor = 'orange'
            hoverEle.style.color = 'white'
        }

        function removeHoverStyle() {
            hoverEle.style.backroundColor = 'white'
            hoverEle.style.color = 'black'
        }
        hoverEle.addEventListener('mouseenter', addHoverStyle);
        hoverEle.addEventListener('mouseleave', removeHoverStyle);  
    </script>
  </body>
</html>