blog/urls.py
from django.urls import path
from . import views

"""
the app_name variable allows us to organise URLs by application and use the
name when reffering to them.
"""
app_name = 'blog'

urlpatterns = [
    # post views
    # path('', views.post_list, name='post_list'),
    path(
        '',
        views.PostListView.as_view(),
        name='post_list'
    ),
    path(
        'tag/<slug:tag_slug>/',
        views.PostListView.as_view(),
        name='post_list_by_tag'
    ),
    path(
        '<int:year>/<int:month>/<int:day>/<slug:post>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        '<int:post_id>/comment/',
        views.post_comment,
        name='post_comment'
    ),

    path(
        'comment/<int:comment_id>/edit/',
        views.edit_comment,
        name='edit_comment'
    ),
    path(
        'comment/<int:comment_id>/delete/',
        views.delete_comment,
        name='delete_comment'
    ),
]

"""
Note: We use angle brackets to capture values from the URL. Any value specified
in the URL pattern as a <parameter> is captured as a string. You use path
converters such as <int:year>, to specifically match and return an integer.
E.g: <slug:post> would specifically match a slug.

Also note that if class based views are going to be used for post list then the
blog/list.html template needs to change as the generic view passes the page
number reuqested in a variable called page_obj. So line 22:
{% include "pagination.html" with page=posts %}  now becomes:
{% include "pagination.html" with page=page_obj %}
"""

blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %}Add a comment{% endblock %}

{% block content %}
  {% if comment %}
    <h2>Your comment has been added.</h2>
    <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
  {% else %}
    {% include "blog/post/includes/comment_form.html" %}
  {% endif %}
{% endblock %}

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% load humanize %} 

{% block content %}
    <h2>{{ post.title }}</h2>
    <p class="date">
        Published {{ post.created_on|naturalday }} by {{ post.author }}
    </p>
    {{ post.body|linebreaks }}
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
    {% endwith %}
    {% for comment in comments %}
    <div class="comment">
      <p class="info">
        Comment {{ forloop.counter }} by {{ comment.user }}
        {{ comment.created_on|naturaltime }}
      </p>
      {{ comment.body|linebreaks }}
      {% if comment.user == user %}
        <a href="{% url 'blog:edit_comment' comment.id %}">Edit |</a>
        <a href="{% url 'blog:delete_comment' comment.id %}"> Delete</a>
    {% endif %}
    </div>
  {% empty %}
    <p>There are no comments yet.</p>
  {% endfor %}
  {% if user.is_authenticated %}
    {% include "blog/post/includes/comment_form.html" %}
  {% else %}
    <p>Please log in to leave a comment.</p>
  {% endif %}
{% endblock %}

{% comment %} the {% with %} template tag is useful for avoiding hitting the 
database or accessing expensive methods multiple times  {% endcomment %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}My Blog{% endblock %}

{% load humanize %} 

{% block content %}
    {% for post in posts  %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="tags">
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}" class="tag-pill">{{ tag.name }}</a>
            {% endfor %}
        </p>
        <p class='date'>
            Published {{ post.created_on|naturalday }} by {{ post.author }}
        </p>
        <p>
            {{ post.body|truncatewords:30|linebreaks }}
        </p>
    {% endfor %}
    {% include "pagination.html" with page=page_obj %}
{% endblock %}

blog/templates/blog/post/omg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
</head>
<body>
    <h2>OMG You hacker that wasn't your comment to be meddling with...</h2>
</body>
</html>